services:
  backend:
    build: backend/.
    ports:
      - "9000:9000"
    container_name: my_backend_container

  frontend:
    build: frontend/.
    ports:
      - "8000:8000"
    container_name: my_frontend_container
